import assert from 'node:assert/strict';
import {neutralPose,validPose,orbitalStep,orbitalShift,radialShift,WebcamFootwork,segmentSphere,segmentCapsule,segmentSphereContact,segmentCapsuleContact,PunchDetector,PoseRenderBuffer,PUNCH,COMBAT,punchDamage,punchPower,punchTier,measurePunch,regression,FightJournal,resolvePunchBox} from '../viewer/boxing_core.mjs';
assert(validPose(neutralPose()));assert(!validPose([[NaN,0,0]]));
assert(Math.abs(segmentSphereContact([-1,0,0],[1,0,0],[0,0,0],.1)-.45)<1e-9);
assert(Math.abs(segmentCapsuleContact([-2,.5,0],[2,.5,0],[0,0,0],[0,1,0],.2)-.45)<1e-9);
assert(segmentCapsule([-2,.5,0],[2,.5,0],[0,0,0],[0,1,0],.2));
assert(!segmentSphere([-1,1,0],[1,1,0],[0,0,0],.1));
assert(!segmentCapsule([-2,1.5,0],[2,1.5,0],[0,0,0],[0,1,0],.2));
const box={head:{c:[0,0,1],r:.2},chin:{c:[0,0,1],r:.1},body:{a:[2,0,1],b:[2,1,1],r:.2},arms:[{a:[-.1,0,.5],b:[.1,0,.5],r:.1}]};
assert.equal(resolvePunchBox([0,0,0],[0,0,2],box).target,'arm');
box.arms[0]={a:[1,0,.5],b:[1,1,.5],r:.1};
assert.equal(resolvePunchBox([0,0,0],[0,0,2],box).target,'head');
console.log('PASS: first-contact sweep, visible guard intercept, open head');
const a={x:0,z:-.6},b={x:0,z:.6};
for(let i=0;i<3600;i++){orbitalStep(a,b,1,.5,1/60);assert(Math.abs(a.x)<=2.55&&Math.abs(a.z)<=2.55);assert(Number.isFinite(a.yaw));}
const mover={x:0,z:-1.1},opponent={x:0,z:0};orbitalShift(mover,opponent,.28);assert(mover.x>0);orbitalShift(mover,opponent,-.28);assert(Math.abs(mover.x)<1e-9);
radialShift(mover,opponent,.2);assert(Math.abs(mover.z+.9)<1e-9);
const cameraPose=()=>neutralPose().map(v=>[v[0],v[1]-.92,v[2]-3]);
const loc=new WebcamFootwork();
const short=cameraPose();short[15][1]-=.6;
for(let i=1;i<=20;i++)assert(loc.update(short,i*33).calibrating);
assert.equal(loc.reference,null);
let result=loc.update(cameraPose(),21*33);
assert(!result.calibrating&&loc.reference);
for(let i=22;i<=40;i++)result=loc.update(cameraPose(),i*33);
const changed=cameraPose().map(v=>[v[0]+.12,v[1]+.2,v[2]+.15]);
result=loc.update(changed,1400);
assert(Math.abs(result.lateral-.12*1.72/1.67)<1e-8);
assert(result.radial>0);
assert.equal(result.footVisible,undefined);assert.equal(result.contacts,undefined);
console.log('PASS: first plausible pose plays immediately, bad pose rejected, metric translation, no synthetic legs');
const detector=new PunchDetector(),rest=neutralPose();
for(let i=0;i<6;i++)detector.update(rest,i*33);
let events=[];
for(let i=0;i<8;i++){const p=neutralPose();p[12][2]+=.6*Math.min(1,i/4);events.push(...detector.update(p,200+i*33));}
assert.equal(events.length,1);assert(events[0].forceN>80);assert(events[0].extension>=1);
for(let i=0;i<10;i++){const p=neutralPose();p[12][2]+=.6;assert.equal(detector.update(p,500+i*33).length,0);}
const carried=new PunchDetector();
for(let i=0;i<24;i++){const p=neutralPose().map(v=>[v[0],v[1],v[2]+i*.06]);assert.equal(carried.update(p,i*33).length,0);}
const gap=new PunchDetector();gap.update(rest,0);const ext=neutralPose();ext[12][2]+=.65;assert.equal(gap.update(ext,700).length,0);
const frames=Array.from({length:6},(_,i)=>({time:i*30,pose:neutralPose().map(v=>[v[0],v[1],v[2]+i*.03])}));
assert(Math.abs(regression(frames,p=>p[0])[2]-1)<1e-10);
const one=measurePunch(frames,0,80),two=measurePunch(frames,0,160);
assert(Math.abs(two.forceN-one.forceN*2)<1e-8);
assert.equal(measurePunch(frames,0,80,[1,0,0]).forceN,0);
assert.equal(measurePunch(frames,0,80,[0,0,-1]).forceN,0);
assert(measurePunch(frames,0,80,[0,0,1]).forceN>0);
console.log('PASS: LS velocities, arm-extension detection, no repeated punch, carried guard=0, tracking gap reset, mass proportionality');
for(const [forceN,expected]of [[0,0],[45,0],[471,471/85],[1001,1001/85],[1468,1468/85],[2000,2000/85],[2500,2500/85],[9000,2500/85]])assert(Math.abs(punchDamage({forceN})-expected)<1e-9);
assert.equal(punchDamage({forceN:2500,chin:true,dizzy:true,counter:true}),30);
assert.equal(punchDamage({forceN:1000,target:'arm'}),0);
assert.equal(punchDamage({forceN:NaN}),0);
assert(punchDamage({forceN:800,target:'body'})<punchDamage({forceN:800,target:'head'}));
assert.equal(punchTier(1000).label,'CRUSHING');assert.equal(punchTier(1200).label,'DEVASTATING');
const damage=punchDamage({forceN:800});const oldScale=PUNCH.tierScaleN;PUNCH.tierScaleN=1600;assert.equal(punchDamage({forceN:800}),damage);PUNCH.tierScaleN=oldScale;
console.log('PASS: linear Newton damage, independent feedback scale, min/safety ceiling, context multipliers');
const journal=new FightJournal();assert.equal(journal.summary().peak,null);
const first=journal.attempt({hand:0,forceN:1000,speed:3},1);
journal.land(first,{forceN:1000,target:'head',combo:1,speed:3});
journal.land(first,{forceN:2000,target:'head',combo:1});
journal.attempt({hand:1,forceN:1500},2);
const second=journal.attempt({hand:1,forceN:400},3);journal.land(second,{forceN:400,target:'body',combo:2});
const blocked=journal.attempt({hand:1,forceN:2000},4);journal.land(blocked,{forceN:2000,target:'arm',blocked:true});
const sum=journal.summary(60);assert.equal(sum.peak,1000);assert.equal(sum.total,1400);assert.equal(sum.average,700);assert.equal(sum.accuracy,.5);assert.equal(sum.maxComboForce,1400);assert.equal(sum.blocked,1);
assert(Object.values(sum).every(v=>typeof v!=='number'||Number.isFinite(v)));
const buffer=new PoseRenderBuffer();const hook=neutralPose();hook[12]=[.1,1.5,.5];const next=neutralPose();next[12]=[-.1,1.5,.5];
buffer.push(hook,{kind:'smpl',left_wrist:hook[12]},1000);buffer.push(next,{kind:'smpl',left_wrist:next[12]},1033);
assert(buffer.sample(1050,50).pose[12][0]<buffer.sample(1040,50).pose[12][0]);
assert.deepEqual(buffer.sample(1040,0).pose,next);buffer.push(hook,null,1400);assert.deepEqual(buffer.sample(1400,50).pose,hook);
console.log('PASS: force journal, hit-only PEAK/TOTAL, miss/block accuracy, exactly-once resolution, render buffering');

