export const strings={
en:{quality:'Graphics',qualityHigh:'High',qualityBalanced:'Balanced',qualityLow:'Performance',qualityTip:'Lower graphics to prioritize fluid movement.',hits:'hits',englishLanguage:'English',portugueseLanguage:'Portuguese',modern:'Fight night',tier_toque:'Touch',tier_leve:'Light',tier_solido:'Solid',tier_forte:'Strong',tier_pesado:'Heavy',tier_devastador:'Devastating',settings:'Settings',fighter:'Fighter',training:'Training',online:'Online',back:'Back',close:'Close',view:'View',third:'Third person',first:'First person',smoothing:'Smoothing',style:'Style',original:'Original',venue:'Arena',night:'Night',dawn:'Dawn',effects:'Camera shake',depth:'Forward / back',sound:'Sound',volume:'Volume',music:'Music',voice:'Announcer',reducedImpact:'Reduced impact sound',reducedTip:'Disables ear ringing and muffling after a knockout.',mass:'Body mass',massTip:'40–180 kg. Used to estimate punch force.',language:'Language',credits:'Credits',webcam:'Webcam',calibrate:'Calibrate',cameraOn:'Camera on',noCamera:'Turn on webcam',tagline:'BOX WITH YOUR BODY',yourFighter:'YOUR FIGHTER',cameraInstruction:'Step back until your whole body is in frame.',calibrating:'Looking for you… show your whole body.',starting:'Connecting…',tracking:'Tracking',showTorso:'Show your torso',trackingLost:'Tracking lost',cameraError:'Camera unavailable',trackerLoading:'Camera is loading',loadError:'Fighter unavailable',peerError:'Fighter unavailable',soundOn:'Sound on',soundOff:'Sound off',room:'Room',server:'Server',connection:'Connection',relay:'Relay',p2p:'Peer to peer',join:'Join',privacy:'Only poses are sent. Video never leaves your computer.',roomInvalid:'Use ws:// or wss:// and a 3–24 character room code.',connecting:'Connecting',joined:'Connected',waiting:'Waiting',disconnected:'Disconnected',connectionError:'Connection failed',result:'Result',victory:'Victory',defeat:'Defeat',draw:'Draw',knockout:'Knockout',decision:'Points',peak:'PEAK',total:'TOTAL FORCE',average:'AVERAGE',accuracy:'ACCURACY',newPeak:'NEW PEAK',previousPeak:'Previous peak',headPeak:'Head',bodyPeak:'Body',combo:'Combo',fastest:'Fastest',chin:'On the chin',blocks:'Blocks',perMinute:'Punches / min',damageReceived:'Damage taken',receivedPeak:'Hardest received',forceTip:'Camera estimate, in newtons.',timeline:'Punch timeline',hit:'Hit',miss:'Miss',blocked:'Blocked',of:'of',record:'Record debug',recording:'Recording',saving:'Saving',recordSaved:'Saved',recordError:'Recording failed',recordOverlay:'Mirrored webcam + latest NLF',recordSource:'NLF source • mirrored view',recordAvatar:'Final avatar • mirrored view',recordOverlay:'Mirrored webcam + latest NLF',loadingLabel:'Loading fighters',brandLabel:'HEAVY HANDS, home',arenaLabel:'HEAVY HANDS boxing ring',smoothTip:'0% disables smoothing. 100% stabilizes motion.'},
pt:{quality:'Gráficos',qualityHigh:'Alto',qualityBalanced:'Equilibrado',qualityLow:'Desempenho',qualityTip:'Reduza os gráficos para priorizar movimentos fluidos.',hits:'acertos',englishLanguage:'Inglês',portugueseLanguage:'Português',modern:'Noite de luta',tier_toque:'Toque',tier_leve:'Leve',tier_solido:'Sólido',tier_forte:'Forte',tier_pesado:'Pesado',tier_devastador:'Devastador',settings:'Ajustes',fighter:'Lutador',training:'Treino',online:'Online',back:'Voltar',close:'Fechar',view:'Visão',third:'Terceira pessoa',first:'Primeira pessoa',smoothing:'Suavização',style:'Estilo',original:'Original',venue:'Arena',night:'Noite',dawn:'Amanhecer',effects:'Tremor de câmera',depth:'Avanço / recuo',sound:'Som',volume:'Volume',music:'Música',voice:'Narrador',reducedImpact:'Som de impacto reduzido',reducedTip:'Desliga o zumbido e o abafamento após um nocaute.',mass:'Massa corporal',massTip:'40–180 kg. Usada para estimar a força do soco.',language:'Idioma',credits:'Créditos',webcam:'Webcam',calibrate:'Calibrar',cameraOn:'Webcam ligada',noCamera:'Ligar webcam',tagline:'BOXE COM O SEU CORPO',yourFighter:'SEU LUTADOR',cameraInstruction:'Afaste-se até o corpo inteiro aparecer na câmera.',calibrating:'Procurando você… mostre o corpo inteiro.',starting:'Conectando…',tracking:'Rastreando',showTorso:'Mostre o tronco',trackingLost:'Rastreamento perdido',cameraError:'Webcam indisponível',trackerLoading:'Webcam carregando',loadError:'Lutador indisponível',peerError:'Lutador indisponível',soundOn:'Som ligado',soundOff:'Som desligado',room:'Sala',server:'Servidor',connection:'Conexão',relay:'Servidor',p2p:'Ponto a ponto',join:'Entrar',privacy:'Só poses são enviadas. O vídeo não sai do seu computador.',roomInvalid:'Use ws:// ou wss:// e um código de sala com 3–24 caracteres.',connecting:'Conectando',joined:'Conectado',waiting:'Aguardando',disconnected:'Desconectado',connectionError:'Falha na conexão',result:'Resultado',victory:'Vitória',defeat:'Derrota',draw:'Empate',knockout:'Nocaute',decision:'Pontos',peak:'PEAK',total:'FORÇA TOTAL',average:'MÉDIA',accuracy:'PRECISÃO',newPeak:'NEW PEAK',previousPeak:'Recorde anterior',headPeak:'Cabeça',bodyPeak:'Corpo',combo:'Combo',fastest:'Mais rápido',chin:'No queixo',blocks:'Defesas',perMinute:'Socos / min',damageReceived:'Dano recebido',receivedPeak:'Maior golpe recebido',forceTip:'Estimativa da câmera, em newtons.',timeline:'Golpes ao longo da luta',hit:'Acerto',miss:'Erro',blocked:'Defesa',of:'de',record:'Gravar debug',recording:'Gravando',saving:'Salvando',recordSaved:'Salvo',recordError:'Falha na gravação',recordOverlay:'Webcam espelhada + último NLF',recordSource:'NLF recebido • vista espelhada',recordAvatar:'Avatar final • vista espelhada',loadingLabel:'Carregando lutadores',brandLabel:'HEAVY HANDS, início',arenaLabel:'Ringue HEAVY HANDS',smoothTip:'0% desliga a suavização. 100% estabiliza o movimento.'}
};
export let language=localStorage.getItem('cornerLanguage')||(navigator.language.toLowerCase().startsWith('pt')?'pt':'en');
if(!strings[language])language='en';
export const t=key=>strings[language][key]||strings.en[key]||key;
export const number=(n,digits=0)=>new Intl.NumberFormat(language==='pt'?'pt-BR':'en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(n);
export function setLanguage(value){
 language=strings[value]?value:'en';localStorage.setItem('cornerLanguage',language);document.documentElement.lang=language==='pt'?'pt-BR':'en';
 for(const el of document.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);
 for(const el of document.querySelectorAll('[data-i18n-title]'))el.title=t(el.dataset.i18nTitle);
 for(const el of document.querySelectorAll('[data-i18n-aria]'))el.setAttribute('aria-label',t(el.dataset.i18nAria));
}
