from pathlib import Path
import subprocess, numpy as np, json, hashlib
from scipy.io import wavfile
root=Path('assets/boxing_audio')
jobs=[('punch_heavy','A_solid,_heavy_punch_#1-1790963020354.mp3',1.3),('punch_super','A_super_strong,_heav_#3-1790963481872.mp3',.8)]
manifest=json.loads((root/'manifest.json').read_text(encoding='utf-8'))
for name,source,duration in jobs:
 data=subprocess.run(['ffmpeg','-v','error','-i',str(root/source),'-t',str(duration),'-ar','44100','-ac','1','-f','f32le','-'],capture_output=True,check=True).stdout
 samples=np.frombuffer(data,dtype='<f4').copy()
 fade=min(2205,len(samples));samples[-fade:]*=np.linspace(1,0,fade)
 # Gentle peak-only soft knee brings the heavy sample into the requested RMS
 # range without clipping, flattening the transient, or boosting beyond−1dBFS.
 if name=='punch_heavy':
  knee=max(np.max(np.abs(samples))*.85,1e-9)
  samples/=np.power(1+np.power(np.abs(samples)/knee,8),1/8)
 rms=np.sqrt(np.mean(samples*samples));peak=np.max(np.abs(samples))
 gain=min(10**(-17/20)/max(rms,1e-9),10**(-1/20)/max(peak,1e-9))
 samples*=gain
 target=root/(name+'.wav');wavfile.write(target,44100,(samples*32767).astype(np.int16))
 record={'name':name,'file':target.name,'author':'Project owner (ElevenLabs)','license':"Owner's ElevenLabs plan terms",'source':source,'seconds':round(len(samples)/44100,3),'changes':f'Trimmed to {duration}s; 50ms fade-out; mono PCM16 44.1kHz; gain {20*np.log10(gain):.2f}dB; '+('gentle peak soft knee; ' if name=='punch_heavy' else '')+'peak <= -1dBFS','sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'rmsDb':round(float(20*np.log10(np.sqrt(np.mean(samples*samples)))),2),'peakDb':round(float(20*np.log10(np.max(np.abs(samples)))),2)}
 manifest=[r for r in manifest if r['name']!=name]+[record]
 print(record)
(root/'manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
credits=(root/'CREDITS.md').read_text(encoding='utf-8')
if 'punch_heavy.wav' not in credits:
 credits+='\n\nHEAVY HANDS additions (2026-10-02): punch_heavy.wav and punch_super.wav were generated by the project owner with ElevenLabs under the terms of their plan. Original MP3s are retained. Converted to mono 44.1 kHz PCM16, trimmed to 1.3 / 0.8 seconds, faded over 50 ms, gain matched with peaks at or below -1 dBFS. Exact source names, gains, measured levels and SHA-256 hashes are in manifest.json.\n\nVictor announcer: project-owner ElevenLabs generation, 37 clips from victor_clips/manifest.json. Original WAVs retained; live mix applies short reverb, bass shelf and a quiet detuned double. No third-party narrator samples were added.\n'
(root/'CREDITS.md').write_text(credits,encoding='utf-8')
