from pathlib import Path
root=Path(__file__).resolve().parents[1]/'viewer';p=root/'boxing.js';s=p.read_text(encoding='utf-8')
s="import {BoxingAudio} from '/static/boxing_audio.js';\n"+s
s=s.replace("const $=id=>document.getElementById(id), keys=new Set();", "const $=id=>document.getElementById(id), keys=new Set(),sound=new BoxingAudio();let effect=null,lastEffect=0;")
s=s.replace("$('smooth').value=smooth;", "$('audio').checked=sound.enabled;$('volume').value=sound.volume*100;$('audio').onchange=()=>sound.setEnabled($('audio').checked);$('volume').oninput=()=>sound.setVolume(Number($('volume').value)/100);\n$('smooth').value=smooth;")
s=s.replace("function enter(isOnline=false){if(!loaded)return;", "function enter(isOnline=false){if(!loaded)return;sound.start().catch(e=>$('trackingStatus').textContent=e.message);")
s=s.replace("function exit(){active=false;", "function exit(){sound.stop();active=false;")
s=s.replace("function reset(){finalResult=null;", "function reset(){finalResult=null;effect=null;lastEffect=0;")
s=s.replace("if(m.result)finish(m.result,false);", "if(m.effect&&m.effect.seq>lastEffect){lastEffect=m.effect.seq;impact(m.effect.pos,m.effect.blocked);notify(m.effect.blocked?'Bloqueio':'Golpe limpo',.6);}if(m.result)finish(m.result,false);")
s=s.replace("type:'state',clock,round,result:finalResult", "type:'state',clock,round,effect,result:finalResult")
s=s.replace("function impact(pos,blocked){", "function impact(pos,blocked){sound.hit(blocked);")
s=s.replace("impact(current,blocked);notify", "effect={seq:(effect?.seq||0)+1,pos:current,blocked};impact(current,blocked);notify")
s=s.replace("round++;clock=90;", "round++;clock=90;sound.bell();")
s=s.replace("active=false;$('resultTitle')", "active=false;sound.bell();sound.stop();$('resultTitle')")
s=s.replace("last=now;acc+=dt;", "last=now;sound.update(dt);acc+=dt;")
p.write_text(s,encoding='utf-8')
p=root/'boxing.html';s=p.read_text(encoding='utf-8').replace('<input id="audio" type="checkbox" disabled> Som • em produção','<input id="audio" type="checkbox"> Sons do ringue')
s=s.replace('</label></dialog>\n<dialog id="match">','</label><label>Volume<input id="volume" type="range" min="0" max="100" value="50"></label><p class="muted">Impactos, sino e torcida em camadas. <a href="/assets/boxing_audio/CREDITS.md" target="_blank" rel="noopener">Créditos dos sons</a></p></dialog>\n<dialog id="match">')
p.write_text(s,encoding='utf-8')
