from pathlib import Path
root=Path(__file__).resolve().parents[1]/'viewer';p=root/'boxing.js';s=p.read_text(encoding='utf-8')
s=s.replace("'#b2d5ff','#161926',1.1", "'#b2d5ff','#161926',.65")
s=s.replace("-4,8,2,95", "-4,8,2,135").replace("4,7,-4,90", "4,7,-4,78").replace("1,8,4,55", "1,8,4,42")
s=s.replace("l.castShadow=true;l.shadow.mapSize.set(1024,1024);", "l.castShadow=x<0;l.shadow.mapSize.set(2048,2048);l.shadow.normalBias=.015;l.shadow.radius=3;")
# Canvas weave and subtle shoe scuffs are authored directly in code.
s=s.replace("cx.fillRect(0,0,1024,1024);cx.strokeStyle", "cx.fillRect(0,0,1024,1024);let noiseSeed=17;for(let y=0;y<1024;y+=4)for(let x=0;x<1024;x+=4){noiseSeed=(noiseSeed*16807)%2147483647;cx.fillStyle='rgba(180,204,225,'+(.015+(noiseSeed%100)/4000)+')';cx.fillRect(x,y,2,1);}cx.strokeStyle='rgba(165,187,209,.03)';cx.lineWidth=1;for(let q=0;q<1024;q+=8){cx.beginPath();cx.moveTo(q,0);cx.lineTo(q,1024);cx.moveTo(0,q);cx.lineTo(1024,q);cx.stroke();}cx.strokeStyle")
s=s.replace("const a={root,group,rig:buildAvatarRig(root),motion:createAvatarMotion(),gloves:[]};", "const a={root,group,rig:buildAvatarRig(root),motion:createAvatarMotion(),gloves:[],clip:{active:{value:0},head:{value:new THREE.Vector3()}}};root.traverse(n=>{if(!n.isMesh)return;for(const m of Array.isArray(n.material)?n.material:[n.material]){m.onBeforeCompile=shader=>{shader.uniforms.cornerClip=a.clip.active;shader.uniforms.cornerHead=a.clip.head;shader.vertexShader='varying vec3 cornerWorld;\\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\\ncornerWorld=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader='varying vec3 cornerWorld;uniform float cornerClip;uniform vec3 cornerHead;\\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\\nif(cornerClip>0.5 && length(cornerWorld.xz-cornerHead.xz)<0.27 && cornerWorld.y>cornerHead.y-0.12) discard;');};m.customProgramCacheKey=()=>\"corner-head-clip-v1\";m.needsUpdate=true;}});")
s=s.replace("const hide=false;", "a.clip.active.value=active&&first&&i===self?1:0;a.clip.head.value.copy(a.rig.bones.get('head').bone.getWorldPosition(new THREE.Vector3()));const hide=false;")
p.write_text(s,encoding='utf-8')
p=root/'boxing.css';s=p.read_text(encoding='utf-8');s+='\n#combatMessage{top:78px;left:35%;right:35%;font:600 16px Barlow Condensed;letter-spacing:2px;color:#f0c483;background:#152134b0;border-radius:4px;line-height:26px}#combatMessage:empty{display:none}@media(max-width:700px){#combatMessage{top:66px;font-size:12px;line-height:20px}}\n';p.write_text(s,encoding='utf-8')
