from pathlib import Path
from playwright.sync_api import sync_playwright

out = Path(__file__).resolve().parents[1] / 'experiments' / 'boxing_review'
out.mkdir(parents=True, exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(args=['--use-angle=d3d11','--ignore-gpu-blocklist'])
    page = browser.new_page(viewport={'width': 1440, 'height': 900})
    page.on('pageerror', lambda e: print('PAGEERROR', e, flush=True))
    print('Loading', flush=True)
    page.goto('http://127.0.0.1:8780/static/boxing.html', wait_until='domcontentloaded')
    page.wait_for_function('window.cornerDebug?.state().loaded', timeout=60000)
    print('Loaded', page.evaluate('cornerDebug.state()'), flush=True)
    page.evaluate('cornerDebug.paused=true')
    page.wait_for_timeout(500)
    page.screenshot(path=str(out / '01-lobby.png'), timeout=60000)
    page.evaluate("document.getElementById('train').click()")
    page.wait_for_timeout(300)
    page.evaluate("async()=>{const {neutralPose}=await import('/static/boxing_core.mjs');cornerDebug.reviewPose(neutralPose());}")
    page.evaluate("cornerDebug.snapCamera=true;cornerDebug.notify('',0);cornerDebug.frame(performance.now())")
    print('Training', page.evaluate('cornerDebug.state()'), flush=True)
    page.screenshot(path=str(out / '02-training.png'), timeout=60000)
    page.evaluate("document.getElementById('settingsButton').click()")
    page.screenshot(path=str(out / '03-settings.png'), timeout=60000)
    page.evaluate("document.getElementById('settings').close(); document.getElementById('view').value='first';cornerDebug.view()")
    page.evaluate('cornerDebug.frame(performance.now())')
    page.evaluate("async()=>{const {neutralPose}=await import('/static/boxing_core.mjs');cornerDebug.reviewPose(neutralPose());cornerDebug.frame(performance.now());}")
    page.screenshot(path=str(out / '04-first.png'), timeout=60000)
    page.evaluate("document.getElementById('view').value='third';cornerDebug.view();cornerDebug.notify('Golpe limpo',5);cornerDebug.frame(performance.now())")
    page.screenshot(path=str(out / '05-hit.png'), timeout=60000)
    page.set_viewport_size({'width': 1366, 'height': 768})
    page.wait_for_timeout(100)
    page.evaluate('cornerDebug.frame(performance.now())')
    page.evaluate("async()=>{const {neutralPose}=await import('/static/boxing_core.mjs');cornerDebug.reviewPose(neutralPose());cornerDebug.frame(performance.now());}")
    page.screenshot(path=str(out / '06-small.png'), timeout=60000)
    browser.close()
